name: build-immortalwrt

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: free-disk-space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Sync upstream
        run: |
          git remote add upstream https://github.com/VIKINGYFY/immortalwrt.git
          git config pull.rebase true
          git pull upstream main --rebase
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main

      - name: Cache dl directory
        uses: actions/cache@v3
        with:
          path: dl
          key: dl-${{ runner.os }}-${{ hashFiles('config/myconfig') }}
          restore-keys: |
            dl-${{ runner.os }}-

      - name: Cache build_dir
        uses: actions/cache@v3
        with:
          path: build_dir
          key: build_dir-${{ runner.os }}-${{ hashFiles('config/myconfig') }}
          restore-keys: |
            build_dir-${{ runner.os }}-

      - name: Install build dependencies
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
            bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
            g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
            libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
            libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
            ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
            python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
            upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd

      - name: Setup ccache
        run: |
          echo 'export CC="ccache gcc"' >> $GITHUB_ENV
          echo 'export CXX="ccache g++"' >> $GITHUB_ENV
          echo 'export PATH="/usr/lib/ccache:$PATH"' >> $GITHUB_ENV

      - name: Build immortalwrt firmware
        run: |
          echo "Start building immortalwrt firmware..."
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cp config/myconfig .config
          make defconfig
          sed -i "s/192.168.1.1/192.168.5.1/g" package/base-files/files/bin/config_generate
          make download -j$(nproc)
          make -j1 V=s
          echo "Build finished."

      - name: Upload firmware to Release
        uses: softprops/action-gh-release@v1
        with:
          files: "bin/targets/**/*.bin"
        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
